/*
 * generated by Xtext 2.12.0
 */
package at.ac.tuwien.big.ide.contentassist.antlr;

import at.ac.tuwien.big.ide.contentassist.antlr.internal.InternalStlParser;
import at.ac.tuwien.big.services.StlGrammarAccess;
import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class StlParser extends AbstractContentAssistParser {

	@Inject
	private StlGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalStlParser createParser() {
		InternalStlParser result = new InternalStlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getNamedElementAccess().getAlternatives(), "rule__NamedElement__Alternatives");
					put(grammarAccess.getComponentAccess().getAlternatives(), "rule__Component__Alternatives");
					put(grammarAccess.getStoreAccess().getAlternatives(), "rule__Store__Alternatives");
					put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getSystemAccess().getGroup(), "rule__System__Group__0");
					put(grammarAccess.getAreaAccess().getGroup(), "rule__Area__Group__0");
					put(grammarAccess.getItemTypeAccess().getGroup(), "rule__ItemType__Group__0");
					put(grammarAccess.getComponentAccess().getGroup_5(), "rule__Component__Group_5__0");
					put(grammarAccess.getServiceAccess().getGroup(), "rule__Service__Group__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getConnectorAccess().getGroup(), "rule__Connector__Group__0");
					put(grammarAccess.getSlotAccess().getGroup(), "rule__Slot__Group__0");
					put(grammarAccess.getItemGeneratorAccess().getGroup(), "rule__ItemGenerator__Group__0");
					put(grammarAccess.getItemGeneratorAccess().getGroup_2(), "rule__ItemGenerator__Group_2__0");
					put(grammarAccess.getStoreAccess().getGroup_1(), "rule__Store__Group_1__0");
					put(grammarAccess.getWasteStoreAccess().getGroup(), "rule__WasteStore__Group__0");
					put(grammarAccess.getProductStoreAccess().getGroup(), "rule__ProductStore__Group__0");
					put(grammarAccess.getBufferAccess().getGroup(), "rule__Buffer__Group__0");
					put(grammarAccess.getMachineAccess().getGroup(), "rule__Machine__Group__0");
					put(grammarAccess.getConveyorAccess().getGroup(), "rule__Conveyor__Group__0");
					put(grammarAccess.getTurnTableAccess().getGroup(), "rule__TurnTable__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
					put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getSystemAccess().getNameAssignment_1(), "rule__System__NameAssignment_1");
					put(grammarAccess.getSystemAccess().getItemTypesAssignment_3(), "rule__System__ItemTypesAssignment_3");
					put(grammarAccess.getSystemAccess().getAreasAssignment_4(), "rule__System__AreasAssignment_4");
					put(grammarAccess.getAreaAccess().getNameAssignment_1(), "rule__Area__NameAssignment_1");
					put(grammarAccess.getAreaAccess().getComponentsAssignment_3(), "rule__Area__ComponentsAssignment_3");
					put(grammarAccess.getAreaAccess().getConnectorsAssignment_4(), "rule__Area__ConnectorsAssignment_4");
					put(grammarAccess.getItemTypeAccess().getNameAssignment_1(), "rule__ItemType__NameAssignment_1");
					put(grammarAccess.getItemTypeAccess().getDescriptionAssignment_3(), "rule__ItemType__DescriptionAssignment_3");
					put(grammarAccess.getComponentAccess().getCostAssignment_5_1(), "rule__Component__CostAssignment_5_1");
					put(grammarAccess.getComponentAccess().getServicesAssignment_5_3(), "rule__Component__ServicesAssignment_5_3");
					put(grammarAccess.getComponentAccess().getInputSlotsAssignment_5_4(), "rule__Component__InputSlotsAssignment_5_4");
					put(grammarAccess.getComponentAccess().getOutputSlotsAssignment_5_5(), "rule__Component__OutputSlotsAssignment_5_5");
					put(grammarAccess.getServiceAccess().getNameAssignment_1(), "rule__Service__NameAssignment_1");
					put(grammarAccess.getServiceAccess().getCostAssignment_3(), "rule__Service__CostAssignment_3");
					put(grammarAccess.getServiceAccess().getProcessingTimeAssignment_4(), "rule__Service__ProcessingTimeAssignment_4");
					put(grammarAccess.getServiceAccess().getReliabilityAssignment_5(), "rule__Service__ReliabilityAssignment_5");
					put(grammarAccess.getServiceAccess().getParametersAssignment_8(), "rule__Service__ParametersAssignment_8");
					put(grammarAccess.getParameterAccess().getNameAssignment_1(), "rule__Parameter__NameAssignment_1");
					put(grammarAccess.getConnectorAccess().getEntryAssignment_1(), "rule__Connector__EntryAssignment_1");
					put(grammarAccess.getConnectorAccess().getExitAssignment_3(), "rule__Connector__ExitAssignment_3");
					put(grammarAccess.getSlotAccess().getNameAssignment_1(), "rule__Slot__NameAssignment_1");
					put(grammarAccess.getItemGeneratorAccess().getNameAssignment_1(), "rule__ItemGenerator__NameAssignment_1");
					put(grammarAccess.getItemGeneratorAccess().getGeneratedTypeAssignment_2_1(), "rule__ItemGenerator__GeneratedTypeAssignment_2_1");
					put(grammarAccess.getStoreAccess().getCapacityAssignment_1_1(), "rule__Store__CapacityAssignment_1_1");
					put(grammarAccess.getWasteStoreAccess().getNameAssignment_1(), "rule__WasteStore__NameAssignment_1");
					put(grammarAccess.getProductStoreAccess().getNameAssignment_1(), "rule__ProductStore__NameAssignment_1");
					put(grammarAccess.getBufferAccess().getNameAssignment_1(), "rule__Buffer__NameAssignment_1");
					put(grammarAccess.getMachineAccess().getNameAssignment_1(), "rule__Machine__NameAssignment_1");
					put(grammarAccess.getConveyorAccess().getNameAssignment_1(), "rule__Conveyor__NameAssignment_1");
					put(grammarAccess.getTurnTableAccess().getNameAssignment_1(), "rule__TurnTable__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public StlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
